apiVersion: v1
kind: Pod
metadata:
  name: pk-visu
  label:
    pgm: visu
spec:
  containers:
  - name: pk-visu
    image: visu:latest
    imagePullPolicy: Never
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: pk-secret-aws
          key: access-key-id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: pk-secret-aws
          key: secret-access-key
    ports:
    - name: port-visu
      containerPort: 8988
      hostPort: 8988
      hostIP: 127.0.0.1
      protocol: tcp
    volumeMounts:
    - name: vn-visu
      mountPath: /home/user/donnees
      readOnly: false
    command:
    - python3
    args:
    ## - suivi.py
    - indices.py
    - yy
    ## - -m
    ## - http.server
    ## - 8988
    resources:
      requests:
        mem: 50M
    livenessProbe:
      httpGet:
        scheme: HTTP
        host: 127.0.0.1
        port: 8988
        path: /
      failureThreshold: 5
      initialDelaySeconds: 30
      periodSeconds: 30
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      priviledged: False
      allowPrivilegeEscalation: False
      readOnlyRootFilesystem: False
      capabilities:
      seccompProfile:
        type:
      seLinuxOptions:
        type:
        user:
        role:
      procMount:
      sysctls:
        name:
  volumes:
  - name: vn-visu
    hostPath:
      path: ../../donnees
      type: Directory
  restartPolicy: Never
  terminationGracePeriodSeconds: 3
  hostNetwork: False
  hostPID: False
  hostIPC: False
