FROM docker.io/library/fedora
RUN dnf update -y && \
    dnf install -y python3-matplotlib python3-numpy python3-tornado python3-requests python3-boto3 python3-beautifulsoup4 && \
    dnf clean all && \
    useradd -u 1000 -m -d /home/user user && \
    mkdir -p -m 770 /home/user/.cache/matplotlib /home/user/.config/matplotlib && \
    chgrp user /home/user/.cache/matplotlib /home/user/.config/matplotlib
VOLUME /home/user/donnees
EXPOSE 8988
# COPY requirements.txt /
# RUN python3 -m pip install --upgrade pip && pip install -r /requirements.txt
COPY --chmod=644 HOME__config_matplotlib_matplotlibrc /home/user/.config/matplotlib/matplotlibrc
COPY --chown=0:1000 --chmod=750 src /home/user/bin
USER 1000
# ENV HOME=/home/user
WORKDIR /home/user/bin
# ENTRYPOINT ["python3"]
# CMD ["--version"]
